compiler:
    - gcc
    - clang
os:
    - linux
sudo: required
dist:
    - trusty
env:
    global:
        - GCC_VERSION="4.8"
    matrix:
        - BUILD_TYPE=Debug
        - BUILD_TYPE=Release

before_install:
        - sudo apt-get update -qq
        - sudo apt-get install -qq build-essential
        - sudo apt-get install -qq ruby
script:
  - sh build_in_travis.sh

notifications:
    email:
        - havyhidalgo@gmail.com



